"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 10000     
command_timeout = 1000   


format = """
[░▒▓](#81a1c1)\
[  ](bg:#81a1c1 fg:#2e3440)\
[](bg:#4c566a fg:#81a1c1)\
$directory\
[](fg:#4c566a bg:#3b4252)\
$git_branch\
$git_status\
[](fg:#3b4252 bg:#2e3440)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#2e3440 bg:#242933)\
$time\
[ ](fg:#242933)\
\n$character"""

[directory]
style = "fg:#d8dee9 bg:#4c566a"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#3b4252"
format = '[[ $symbol $branch ](fg:#d8dee9 bg:#3b4252)]($style)'

[git_status]
style = "bg:#3b4252"
format = '[[($all_status$ahead_behind )](fg:#d8dee9 bg:#3b4252)]($style)'

[nodejs]
symbol = ""
style = "bg:#2e3440"
format = '[[ $symbol ($version) ](fg:#88c0d0 bg:#2e3440)]($style)'

[rust]
symbol = ""
style = "bg:#2e3440"
format = '[[ $symbol ($version) ](fg:#88c0d0 bg:#2e3440)]($style)'

[golang]
symbol = ""
style = "bg:#2e3440"
format = '[[ $symbol ($version) ](fg:#88c0d0 bg:#2e3440)]($style)'

[php]
symbol = ""
style = "bg:#2e3440"
format = '[[ $symbol ($version) ](fg:#88c0d0 bg:#2e3440)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#242933"
format = '[[  $time ](fg:#81a1c1 bg:#242933)]($style)'

[character]
success_symbol = "[➜](bold #88c0d0)"
error_symbol = "[➜](bold #bf616a)"